# Generated by Mighty Craxe
{.experimental: "codeReordering".}

proc apOperator[T](val:var T):T {.discardable, inline.} =        
    result = val
    inc(val)

proc bpOperator[T](val:var T):T {.discardable, inline.} =        
    inc(val)
    result = val

template `+`(s:string, i:untyped): string =
    s & $i

template `+`(i:untyped, s:string): string =
    $i & s

template `+`(s1:string, s2:string): string =
    s1 & s2

type
    HaxeArray[T] = ref object of RootObj
        data : seq[T]

proc newHaxeArray[T]() : HaxeArray[T] =
    result = HaxeArray[T]()

template push[T](this:HaxeArray[T], value:T) =
    this.data.add(value)

template pop[T](this:HaxeArray[T]): T =
    let last = this.data.len - 1
    let res = this.data[last]
    delete(this.data, last)
    res

template get[T](this:HaxeArray[T], pos:int): T =
    this.data[pos]

template length[T](this:HaxeArray[T]): int =    
    this.data.len

proc `$`[T](this:HaxeArray[T]) : string {.inline.} =
    result = $this.data

type 
    MyType = ref object of RootObj
        id : int
        name : string

    ArrayTest = ref object of RootObj
    ArrayTestStatic = ref object of RootObj

let ArrayTestStaticInst = ArrayTestStatic()

proc newMyType(id : int, name : string): MyType {.inline.} =
    let this = MyType()
    result = this
    this.id = id
    this.name = name

proc say(this : MyType) : void =
    echo("id: " + this.id + " name: " + this.name)

proc `$`(this : MyType):string {.inline.} =
    result = "MyType" & $this[]

proc main(this : ArrayTestStatic) : void =
    var arr = @[newMyType(1, "Batman"), newMyType(3, "Superman")]
    echo(arr)

proc `$`(this : ArrayTest):string {.inline.} =
    result = "ArrayTest" & $this[]

ArrayTestStaticInst.main()