// Generated by Haxe 4.0.0-rc.2+77068e10c
(function () { "use strict";
var MyType = function() {
};
var ArrayTest = function() { };
ArrayTest.main = function() {
	var arr = [];
	arr.push(33);
	arr.push(22);
	arr.push(11);
	var _g = 0;
	while(_g < arr.length) {
		var it = arr[_g];
		++_g;
		console.log("test/ArrayTest.hx:12:",it++);
	}
};
ArrayTest.main();
})();
